#pragma once
namespace ncnl {
struct AssetEntry { const wchar_t* path; unsigned id; };
static const AssetEntry ASSET_INDEX[]={
    {L"arrow.png",1000},
    {L"chord_emotion/1.gif",1001},
    {L"chord_emotion/2.gif",1002},
    {L"chord_emotion/3.gif",1003},
    {L"chord_emotion/4.gif",1004},
    {L"chord_emotion/5.gif",1005},
    {L"cursor/Link.ani",1006},
    {L"cursor/Text Select.ani",1007},
    {L"cursor/Unavailable.ani",1008},
    {L"cursor/Vertical Resize.ani",1009},
    {L"icon.png",1010},
    {L"res/font.ttf",1011},
    {L"res/penta_dim.png",1012},
    {L"skins/buttons/confirm.png",1013},
    {L"skins/buttons/generate.png",1014},
    {L"skins/buttons/mode_aeolian.png",1015},
    {L"skins/buttons/mode_dorian.png",1016},
    {L"skins/buttons/mode_ionian.png",1017},
    {L"skins/buttons/mode_locrian.png",1018},
    {L"skins/buttons/mode_lydian.png",1019},
    {L"skins/buttons/mode_mixolydian.png",1020},
    {L"skins/buttons/mode_phrygian.png",1021},
    {L"skins/buttons/mode_tab.png",1022},
    {L"skins/buttons/ncnl.png",1023},
    {L"skins/buttons/plugins_tab.png",1024},
    {L"skins/buttons/presets.png",1025},
    {L"skins/buttons/radar_tab.png",1026},
    {L"skins/buttons/refresh.png",1027},
    {L"skins/buttons/save.png",1028},
    {L"skins/buttons/settings.png",1029},
    {L"skins/main.png",1030},
    {L"skins/mode.png",1031},
    {L"skins/plugins.png",1032},
    {L"skins/preset.png",1033},
    {L"skins/radar.png",1034},
};
}
