if(MINGW)
    set(header "${CMAKE_CURRENT_SOURCE_DIR}/vendor/vst3sdk/public.sdk/source/vst/utility/alignedalloc.h")
    file(READ "${header}" source)
    set(original "${source}")
    string(REPLACE "#ifdef _MSC_VER" "#if defined(_MSC_VER) || defined(__MINGW32__)" source "${source}")
    string(REPLACE "#elif defined(_MSC_VER)" "#elif defined(_MSC_VER) || defined(__MINGW32__)" source "${source}")
    string(REPLACE "#if defined(_MSC_VER)" "#if defined(_MSC_VER) || defined(__MINGW32__)" source "${source}")
    string(REPLACE " || defined(__MINGW32__) || defined(__MINGW32__)" " || defined(__MINGW32__)" source "${source}")
    if(NOT source STREQUAL original)
        file(WRITE "${header}" "${source}")
    endif()
    add_compile_definitions(_M_AMD64)
endif()
